require "basic"
require "keybindings"
require "plugins"
require "colorscheme"
require "plugin-config.nvim-tree"
require "plugin-config.bufferline"
require "plugin-config.blankline"
require "plugin-config.lualine"
require "plugin-config.comment"
require "plugin-config.telescope"
require "plugin-config.dashboard"
require "plugin-config.project"
require "plugin-config.nvim-treesitter"
require "plugin-config.lsp"
require "lsp.ui"
require "plugin-config.comment"
require "plugin-config.nvim-cmp"



