# generated by Git for Windows

# xterm：UNIX 系统中最基本的终端类型。
# xterm-256color：支持 256 色的 xterm 终端。
# cygwin：Cygwin 环境下的终端类型。
# linux：Linux 终端类型，通常用于文本模式。
# screen：GNU Screen 多路复用终端。
# export TERM=xterm-256color
test -f ~/.profile && . ~/.profile
test -f ~/.bashrc && . ~/.bashrc
